In [96]:
import pandas as pd
import numpy as np
from numpy import mean
from numpy import std
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np
from numpy import mean
from numpy import std
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.metrics import confusion_matrix

In [97]:
df = pd.read_csv('diabetes_prediction_dataset.csv')

In [98]:
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [99]:
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [100]:
df['smoking_history'].value_counts()

smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

In [101]:
from sklearn.preprocessing import LabelEncoder

In [102]:
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [103]:
df['smoking_history'] = le.fit_transform(df['smoking_history'])

In [104]:
df

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19   
1           0  54.0             0              0                0  27.32   
2           1  28.0             0              0                4  27.32   
3           0  36.0             0              0                1  23.45   
4           1  76.0             1              1                1  20.14   
...       ...   ...           ...            ...              ...    ...   
99995       0  80.0             0              0                0  27.32   
99996       0   2.0             0              0                0  17.37   
99997       1  66.0             0              0                3  27.83   
99998       0  24.0             0              0                4  35.42   
99999       0  57.0             0              0                1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  int64  
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  int64  
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(3), int64(6)
memory usage: 6.9 MB


In [106]:
X = df.drop('diabetes', axis=1)
y = df['diabetes']

In [107]:
X.shape, y.shape

((100000, 8), (100000,))

In [108]:
df['diabetes'].value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

In [109]:
mayority = df[df['diabetes'] == 0]
minority = df[df['diabetes'] == 1]

mayority_undersampling = mayority.sample(n=len(minority), random_state=42)

In [110]:
df_balance= pd.concat([mayority_undersampling, minority])


In [111]:
df_balance['diabetes'].value_counts()

diabetes
0    8500
1    8500
Name: count, dtype: int64

In [112]:
df_balance['heart_disease'].value_counts()

heart_disease
0    15499
1     1501
Name: count, dtype: int64

In [113]:
scaler = MinMaxScaler()

In [114]:
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns.values)
X

gender       age  hypertension  heart_disease  smoking_history  \
0         0.0  1.000000           0.0            1.0              0.8   
1         0.0  0.674675           0.0            0.0              0.0   
2         0.5  0.349349           0.0            0.0              0.8   
3         0.0  0.449449           0.0            0.0              0.2   
4         0.5  0.949950           1.0            1.0              0.2   
...       ...       ...           ...            ...              ...   
99995     0.0  1.000000           0.0            0.0              0.0   
99996     0.0  0.024024           0.0            0.0              0.0   
99997     0.5  0.824825           0.0            0.0              0.6   
99998     0.0  0.299299           0.0            0.0              0.8   
99999     0.0  0.712212           0.0            0.0              0.2   

            bmi  HbA1c_level  blood_glucose_level  
0      0.177171     0.563636             0.272727  
1      0.202031     0.563636             0.000000  
2      0.202031     0.400000             0.354545  
3      0.156863     0.272727             0.340909  
4      0.118231     0.236364             0.340909  
...         ...          ...                  ...  
99995  0.202031     0.490909             0.045455  
99996  0.085901     0.545455             0.090909  
99997  0.207983     0.400000             0.340909  
99998  0.296569     0.090909             0.090909  
99999  0.144958     0.563636             0.045455  

[100000 rows x 8 columns]

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [116]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [117]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [118]:
np.array(y_test)

array([0, 0, 0, ..., 0, 0, 0])

In [119]:
confusion_matrix(y_test, y_pred)

array([[16968,  1331],
       [  593,  1108]])

In [120]:
from sklearn.model_selection import KFold
cv = KFold(n_splits=10, random_state=1, shuffle=True)
scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
print(scores)

[0.9058 0.9017 0.907  0.902  0.9062 0.903  0.9028 0.9017 0.8957 0.9061]


In [121]:
accuracy = cross_val_score(model, X, y, scoring='accuracy', cv=cv)
print('Accuracy: {}'.format(accuracy.mean()*100))
precision = cross_val_score(model, X, y, scoring='precision_weighted', cv=cv)
print('Precision: {}'.format(precision.mean()*100))
recall = cross_val_score(model, X, y, scoring='recall_weighted', cv=cv)
print('Recall: {}'.format(recall.mean()*100))
f1 = cross_val_score(model, X, y, scoring='f1_weighted', cv=cv)
print('F1: {}'.format(f1.mean()*100))

Accuracy: 90.32
Precision: 92.21394533922049
Recall: 90.32
F1: 91.08248436010274


In [122]:
import joblib

joblib.dump(model, 'model.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [127]:
%%writefile app.py

import streamlit as st
import numpy as np
import pickle
import joblib

scaler = joblib.load('scaler.pkl')
model = joblib.load('model.pkl')

st.set_page_config(
    page_title= "Diabetes Predicted Dashboard",
    page_icon= "🩺"
)

st.sidebar.title('Menu')
menu = st.sidebar.radio(
    "Pilih Halaman:",
    ("Home", "BMI", "Cek Diabetes")
)

if menu == "Home":
    st.title("Diabetes Prediksi", anchor=None, help=None)

    st.markdown(''' Diabetes adalah penyakit mematikan yang terus meningkat di dunia. :blue-background[Pada 2024, 589 juta orang hidup dengan diabetes, 
    dan angka ini diprediksi naik jadi 853 juta pada 2050 (IDF)]. :blue-background[Di Indonesia, 19,5 juta] orang menderita diabetes pada 2021, 
    dan lebih dari 73% penderita belum terdiagnosis (Kemenkes RI). Diabetes bisa menyebabkan serangan jantung, stroke, gagal ginjal, 
    bahkan amputasi (WHO). Deteksi dini sangat penting agar kita bisa mencegah komplikasi serius. ''')

    st.markdown(''' Diabetes adalah :blue-background[pembunuh senyap] yang sering kali tidak terdeteksi hingga menimbulkan komplikasi serius. 
    Keterlambatan dalam diagnosis dan pengobatan menjadi penyebab utama tingginya angka kematian akibat penyakit ini.''')

    st.subheader('Fakta Mengerikan tentang Kematian Akibat Diabetes')

    with st.container():
        st.error("1️⃣ **Setiap 5 detik, 1 orang meninggal akibat diabetes.** Pada tahun 2021, diabetes menyebabkan sekitar 6,7 juta kematian di seluruh dunia.")

    with st.container():
        st.error("2️⃣ **Di Indonesia, pada tahun 2021, tercatat sekitar 236.711 kematian terkait diabetes.**")

    with st.container():
        st.error('3️⃣ **73,7% penderita diabetes di Indonesia tidak terdiagnosis, menyebabkan banyak kasus baru diketahui setelah komplikasi muncul.** ')

elif menu == "BMI":
    st.title('Cek BMI mu!')
    with st.form('BMI Form'):
        bb = st.number_input("Berat Badan (Kg)",value=None, placeholder="Ketikan Berat Badanmu...")
        tb = st.number_input("Tinggi Badan (Cm)",value=None, placeholder="Ketikan Tinggi Badanmu...")
        submitted = st.form_submit_button("Hitung BMI")

        if submitted:
            tb_m = tb/100
            bmi = bb/ (tb_m ** 2)
            if bmi < 18.5:
                st.info(f'BMI anda adalah {bmi: .2f} dan terkategori Berat badan kurang')
            elif 18.5 <= bmi < 24.9:
                st.success(f'BMI anda adalah {bmi: .2f} dan terkategori Berat badan Normal')
            elif 25 <= bmi < 29.9:
                st.warning(f'BMI anda adalah {bmi: .2f} dan terkategori Berat badan berlebih')
            else:
                st.error(f'BMI anda adalah {bmi: .2f} dan terkategori obesitas')

elif menu == "Cek Diabetes":
    st.title("Ayo cek diabetes sedini mungkin!")
    with st.form("Diabetes Form"):
        gender = st.selectbox("Jenis Kelamin:", ["Laki-laki", "Perempuan"])
        age = st.number_input("Usia:",value=None, placeholder="Ketikan Usiamu...")
        hypertension = st.selectbox("Hipertensi:", ["Ya", "Tidak"])
        smoking_history = st.selectbox("Riwayat Merokok:", ["No Info", "never", "former", "current", "ever"])
        heart_disease = st.selectbox("Riwayat Penyakit Jantung:", ["Ya", "Tidak"])
        bmi = st.number_input("BMI:",value=None, placeholder="Ketikan BMImu...")
        HbA1c_level = st.number_input("HbA1c Level:",value=None, placeholder="Ketikan HbA1c Levelmu...")
        glucose_level = st.number_input("Kadar Gula:",value=None, placeholder="Ketikan Kadar Gulamu...")
        submitted = st.form_submit_button("Cek Diabetes")

        if submitted:
            # Label Encoding manual (harus sama seperti saat training!)
            gender_encoded = 1 if gender == "Perempuan" else 0
            hypertension_encoded = 1 if hypertension == "Ya" else 0
            heart_disease_encoded = 1 if heart_disease == "Ya" else 0

            # Untuk smoking_history (harus urutannya sama!)
            mapping_smoking = {
                "No Info": 0,
                "never": 1,
                "former": 2,
                "current": 3,
                "ever": 4
            }
            smoking_encoded = mapping_smoking[smoking_history]

            # Susun input array sesuai urutan fitur saat training
            input_data = np.array([[gender_encoded, age, hypertension_encoded, heart_disease_encoded,
                                    smoking_encoded, bmi, HbA1c_level, glucose_level]])

            # Prediksi
            scaled_input = scaler.transform(input_data)
            prediksi = model.predict(scaled_input)

            # Tampilkan hasil prediksi
            if prediksi[0] == 1:
                st.error("⚠️ Anda berisiko terkena diabetes. Segera konsultasikan ke dokter.")
            else:
                st.success("✅ Anda tidak terdeteksi diabetes. Tetap jaga kesehatan!")


Overwriting app.py


In [124]:
from pyngrok import ngrok
import threading
import os

def run_streamlit():
    os.system('streamlit run app.py --server.port 8001')
thread = threading.Thread(target=run_streamlit)
thread.start()

public_url = ngrok.connect(addr='8001')
print(public_url)

NgrokTunnel: "https://d327-36-72-205-226.ngrok-free.app" -> "http://localhost:8001"
